SickBeard.Schedule/Controllers/AuthenticationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using SickBeard.Schedule.Models;

namespace SickBeard.Schedule.Controllers
{
    public class AuthenticationController : Controller
    {
        public ActionResult Login(String returnUrl)
        {
            return View(new LoginModel() { ReturnUrl = returnUrl });
        }

        [Authorize]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return Redirect("/Login");
        }

        [Authorize]
        public ActionResult Settings()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model)
        {
            if (ModelState.IsValid && Membership.ValidateUser(model.Username, model.Password))
            {
                FormsAuthentication.SetAuthCookie(model.Username, model.Remember);
                return string.IsNullOrEmpty(model.ReturnUrl) ? Redirect("/Schedule") : Redirect(model.ReturnUrl);
            }

            if (ModelState.IsValid) ModelState.AddModelError("", "The combination of username and password is incorrect.");
            model.Password = string.Empty;
            return View(model);
        }

    }
}

SickBeard.Schedule/Views/Authentication/Login.cshtml
@model SickBeard.Schedule.Models.LoginModel

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout_Auth.cshtml";
}

<div class="chillflix-logo"></div>

@using (Html.BeginForm("Login", "Authentication", FormMethod.Post, new { @class = "login-form" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false)
    @Html.HiddenFor(m => m.ReturnUrl)

    @Html.TextBoxFor(m => m.Username, new { placeholder = "Username", autocomplete = "off" })
    @Html.PasswordFor(m => m.Password, new { placeholder = "Password" })

    @Html.LabelFor(m => m.Remember)
    @Html.CheckBoxFor(m => m.Remember)

    <input type="submit" value="Login" class="submit" />
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SickBeard.Schedule/Views/Authentication/Settings.cshtml
@{
    ViewBag.Title = "Account Settings";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Account Settings</h2>